### ISSUE TITLE
0.11.9的ng-zorro-antd-mobile无法正常添加依赖和生成组件

### ISSUE THREAD

**Issue by DawnSouther** [NG-ZORRO/ng-zorro-antd-mobile#395]
## Version
0.11.9
## Environment
nodev11.14.0, @angular/cli 7.3.6
## Reproduction link
[https://ng-zorro-antd-mobile-start.stackblitz.io](https://ng-zorro-antd-mobile-start.stackblitz.io)
## Steps to reproduce
ng add ng-zorro-antd-mobile
or
ng g ng-zorro-antd-mobile:tab-bar-basic --name=tab
## What is expected?
正确添加依赖或者正确创建组件
## What is actually happening?
no schema with key or ref "https://json-schema.org/schema"
Error: no schema with key or ref "https://json-schema.org/schema"
    at Ajv.validate (I:\develop\WorkSpaces\ng-demo\node_modules\ajv\lib\ajv.js:91:19)
    at Ajv.validateSchema (I:\develop\WorkSpaces\ng-demo\node_modules\ajv\lib\ajv.js:172:20)
    at Ajv._addSchema (I:\develop\WorkSpaces\ng-demo\node_modules\ajv\lib\ajv.js:305:10)
    at Ajv.compile (I:\develop\WorkSpaces\ng-demo\node_modules\ajv\lib\ajv.js:111:24)
    at CoreSchemaRegistry.flatten (I:\develop\WorkSpaces\ng-demo\node_modules\@angular-devkit\core\src\json\schema\registry.js:173:45)
    at Object.parseJsonSchemaToOptions (I:\develop\WorkSpaces\ng-demo\node_modules\@angular\cli\utilities\json-schema.js:201:44)
    at AddCommand.runSchematic (I:\develop\WorkSpaces\ng-demo\node_modules\@angular\cli\models\schematic-command.js:306:37)
    at AddCommand.executeSchematic (I:\develop\WorkSpaces\ng-demo\node_modules\@angular\cli\commands\add-impl.js:134:31)
    at AddCommand.run (I:\develop\WorkSpaces\ng-demo\node_modules\@angular\cli\commands\add-impl.js:43:25)
    at AddCommand.validateAndRun (I:\develop\WorkSpaces\ng-demo\node_modules\@angular\cli\models\command.js:124:31)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
## Other?
经检查， 是0.11.9的bug.
\node_modules\ng-zorro-antd-mobile目录下没有/scripts/schematics/template/schema.json文件夹，
我尝试过退回到nodejs的v10版本，@angular/cli退回到7.3.6，均无法解决，将ng-zorro-antd-mobile退回到0.11.8，可解决问题

**Comment by ferried** [comment]
<a href="http://ng.mobile.ant.design/#/docs/getting-started/zh">手动引入方式</a>

**Comment by fisherspy** [comment]
@DawnSouther @ferried 0.12.0版本已修复。
