### ISSUE TITLE
无法与 ionic 共同使用

### ISSUE THREAD

**Issue by indesigncs** [NG-ZORRO/ng-zorro-antd-mobile#828]
## Version
5.0.1
## Environment
windows10    ionic最新版
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-bbcsxs?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-bbcsxs?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
哪怕只使用一个BUTTON都发生错误
## What is expected?
正常显示页面
## What is actually happening?
ERROR Error: Uncaught (in promise): Error: inject() must be called from an injection context
Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:4764:1)
    at ɵɵinject (core.js:4774:1)
    at Module.ɵɵdirectiveInject (core.js:14753:1)
    at NodeInjectorFactory.ButtonComponent_Factory [as factory] (ng-zorro-antd-mobile.js:4730:120)
    at getNodeInjectable (core.mjs:3556:44)
    at instantiateAllDirectives (core.mjs:10298:27)
    at createDirectivesInstances (core.mjs:9647:5)
    at ɵɵelementStart (core.mjs:14536:9)
    at HomePage_Template (template.html:17:35)
    at executeTemplate (core.mjs:9618:9)
    at resolvePromise (zone.js:1255:1)
    at resolvePromise (zone.js:1209:1)
    at zone.js:1321:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
    at Object.onInvokeTask (core.mjs:25463:33)
    at ZoneDelegate.invokeTask (zone.js:433:1)
    at Zone.runTask (zone.js:205:1)
    at drainMicroTaskQueue (zone.js:620:1)

**Comment by wancmx** [comment]
你可以在 tsconfig.app.json 文件的 compilerOptions 属性内加上以下代码

`"paths": { "@angular/*": [ "./node_modules/@angular/*" ] }`

需要注意一下node_modules的路径，有可能需要使用如下代码

`"paths": { "@angular/*": [ "../node_modules/@angular/*" ] }`

![image](https://user-images.githubusercontent.com/58903988/156540001-2a3bce65-2edf-4f86-8f02-14a21d297966.png)
