### ISSUE TITLE
Toast 服务出现js错误

### ISSUE THREAD

**Issue by zy8008** [NG-ZORRO/ng-zorro-antd-mobile#837]
## Version
6.0.0
## Environment
Angular:13.2.6;TypeScript: 4.5.5;Node: 16.14.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-dljack?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-dljack?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
1，新建button ，并添加click事件
2，点击事件，调用 ToastService.info()事件，代码：this._toast.info('请输入手机号！',4000, undefined, false, 'top');
3，第一次点击button
4，再次点击button           
## What is expected?
两次能正确显示提醒信息：请输入手机号！
## What is actually happening?
第一次成功显示信息后，报JS错误：
 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at http://localhost:4200/vendor.js:128845:23
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3487:26)
    at Object.onInvoke (http://localhost:4200/vendor.js:92889:33)
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3486:52)
    at Zone.run (http://localhost:4200/polyfills.js:3249:43)
    at NgZone.run (http://localhost:4200/vendor.js:92743:28)
    at ToastService.hide (http://localhost:4200/vendor.js:128843:18)
    at http://localhost:4200/vendor.js:128772:16
    at timer (http://localhost:4200/polyfills.js:5493:41)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3521:31)
第二次点击后不会再显示提示信息，但报同样的错误

**Comment by mond70345** [comment]
我也遇到这个问题，什么时候修复？
